name: Build and Push Docker Images

on:
  push:
    branches:
      - "main"

jobs:
  nextjs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Calculate Short SHA
        id: css
        run: echo "ss=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./NextJS
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/deepsight-frontend:${{ steps.css.outputs.ss }}
            ${{ secrets.DOCKERHUB_USERNAME }}/deepsight-frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  django:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Calculate Short SHA
        id: css
        run: echo "ss=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./Django
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/deepsight-backend:${{ steps.css.outputs.ss }}
            ${{ secrets.DOCKERHUB_USERNAME }}/deepsight-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
